server:
  port: 8099

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exam?characterEncoding=utf8
    username: root
    password: 345
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.MySQL5Dialect